### ISSUE TITLE
Stage 1 Sharding

### ISSUE THREAD

**Issue by ianagbip1oti** [princesslana/ErisCasper.java#120]
https://discordapp.com/developers/docs/topics/gateway#sharding

Accept EC_SHARD_ID and EC_SHARD_NUM as environment variables and send these to Discord.

Part of #105

**Comment by CoreyShupe** [comment]
I think sharding should be done though the create method:
ErisCasper.create(token, max_shards, shard_id)
I only say this since using them as environment variables stops it from being capable of running multiple shards in the same program, which could be useful for the user.

**Comment by ianagbip1oti** [comment]
Sure, there would be a method like this, but the default `create` method should check the environment variables.

**Comment by CoreyShupe** [comment]
I was thinking system property variables rather than environment variables since it makes more sense imo. Environment variables are supposed to be static throughout the machine, system properties are manipulated per program. So I just setup system properties to handle stage 1 sharding along with param values.

**Comment by ianagbip1oti** [comment]
For using system properties as well as env vars see #106 

Using environment variables config I want to support as it's a best practice: https://12factor.net/config

**Comment by CoreyShupe** [comment]
I implemented system properties as well as env variables for handling the bot token, but we don't currently have a config system setup? I could implement environment variables for sharding, it wouldn't take too too much time.

**Comment by ianagbip1oti** [comment]
Yes, we don't currently have a config system setup, that's what #106 is about.

I would prefer using a consistent method of config (being environment variables) until #106 is in place and supports other methods
