### ISSUE TITLE
Add checkstyle to build

### ISSUE THREAD

**Issue by ianagbip1oti** [princesslana/ErisCasper.java#153]
Some code style preferences are not picked up by spotless with google java format.

For example, avoid start imports, always uses braces on if, etc.

Add checkstyle to the build process, as part of verify

**Comment by CoreyShupe** [comment]
Working on creating a maven plugin for checking things, I recommend making a checklist of what you want the check style to assert. I'll start with brace checking, and star import checking.
Started here https://github.com/CoreyShupe/ErisCasper-Checkstyle
Another possible option is PRing spotless.

**Comment by ianagbip1oti** [comment]
When I say checkstyle, I mean http://checkstyle.sourceforge.net/

**Comment by CoreyShupe** [comment]
Well I'm smart... oh well, good practice ig, I'll look into implementing all of that.
